
Sys.setenv(FALK_EXTENDED_USER_RIGHTS= "[{\"A\":85,\"R\":\"SC\",\"U\":105588},{\"A\":85,\"R\":\"LU\",\"U\":105588},{\"A\":85,\"R\":\"LU\",\"U\":601161},{\"A\":85,\"R\":\"LU\",\"U\":4212372}]")
Sys.setenv(FALK_APP_ID="85")
Sys.setenv(FALK_USER_EMAIL="jesus@sky.no")
Sys.setenv(FALK_USER_FULLNAME="Lotta")
Sys.setenv(MYSQL_DB_LOG="db_log")
Sys.setenv(MYSQL_DB_AUTOREPORT="db_autoreport")
Sys.setenv(MYSQL_DB_DATA="DegenNakkeReportDataStaging")
# Sys.setenv(MYSQL_DB_DATA="nakke")
Sys.setenv(MYSQL_HOST="localhost") # "db")
Sys.setenv(MYSQL_USER="root")
Sys.setenv(MYSQL_PASSWORD="root")
Sys.setenv(R_RAP_INSTANCE="QAC")
Sys.setenv(R_RAP_CONFIG_PATH="data-raw/config") # "/home/rstudio/nakke/data-raw/config")
Sys.setenv(SHINYPROXY_USERNAME="ttsk")
Sys.setenv(SHINYPROXY_USERGROUPS="pilot")
Sys.setenv(USERORGID="pilot")

