---
title: "Shinykommandoer"
author: "Lena Ringstad Olsen"
date: "6 april 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Formål

Ønsker å sammenfatte noen av de viktigste funksjonene i Shiny så jeg klarer å huske hva de gjør og hvilken som skal brukes når.


## Kommandoer, UI, dvs. det som vises på skjermen

* fluidPage() - A fluid page layout consists of rows which in turn include columns. Kan velge å spesifisere rubrikker ved sidebarLayout eller spesifikt i rader og kolnner.

* tabsetPanel() - deler inn i arkfaner (tabs)

*navlistPanel() - 


Segmenting layouts using the tabsetPanel() and navlistPanel() functions.

Creating applications with multiple top-level components using the navbarPage() function


## server - alle beregninger som ligger bak


## tooltips
library(ggvis)
df %>% ggvis(~x, ~y) %>% layer_points() %>% 
    add_tooltip(function(x) paste0(names(x), ": ", 
                format(x), collapse = "<br />"), "hover") %>%
    bind_shiny("plot_id")
And then in ui.R, to place the plot you use:

ggvisOutput("plot_id")

## From ui.R: Adds a tooltip to element with inputId = "someInput"
## with text, "This is an input.", that appears to the left on hover.
bsTooltip(id = "someInput", title = "This is an input",
          placement = "left", trigger = "hover")

## From server.R: Add the same tooltip as above
addTooltip(session, id = "someInput", title = "This is an input.",
           placement = "left", trigger = "hover")



## html-koder
* hr() - horisontal strek som skiller mellom paneler på sida
* br() - line break element


http://shiny.rstudio.com/articles/tag-glossary.html

Bibliotek over html-koder:
https://www.w3schools.com/tags/


## Legge til innlogging (autentisering)

https://auth0.com/blog/adding-authentication-to-shiny-server/



# Les mer om
## Building a pipeline for reproducible data screening and quality control	
Claus Ekstrøm
Anne Helby Petersen

Overview
One of the biggest challenges for a data analyst is to ensure the reliability of the data since the validity of the conclusions from the analysis hinges on the quality of the input data. This tutorial will cover the workflow of data screening and -validation that transforms raw data into data that can be used for statistical analysis. 

In particular, we will discuss organizing research projects, tidy data formats, internal and external validity of data, requirements for reproducible research, the dataMaid R package for customized data screening, the *assertr* and *assertive* R packages for data validation and data validation rule sets, and how to produce code books that summarize the final result of the data screening process and provide a starting point for the subsequent statistical analyses.

## Package: data.table
